# Generated by Django 5.0.3 on 2024-03-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_comment_subcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='subcomment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Subcomment',
        ),
    ]
